version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@layer0/*'
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@layer0/*'
